package com.belwar.aiseexcelprocessor;

public class ExcelStrUtil {
    public static String[] patogolyIds = { "1",
                                    "2",
                                    "3",
                                    "3.1",
                                    "3.2",
                                    "3.3",
                                    "3.4",
                                    "4",
                                    "4.1",
                                    "4.2",
                                    "4.3",
                                    "4.4",
                                    "4.5",
                                    "4.6",
                                    "4.7",
                                    "5",
                                    "5.1",
                                    "5.2",
                                    "6",
                                    "6.1",
                                    "6.2",
                                    "6.3",
                                    "6.4",
                                    "7",
                                    "7.1",
                                    "7.2",
                                    "7.3",
                                    "7.4",
                                    "7.5",
                                    "8",
                                    "8.1",
                                    "8.2",
                                    "8.3",
                                    "8.4",
                                    "9",
                                    "9.1",
                                    "9.2",
                                    "9.3",
                                    "9.4",
                                    "9.5",
                                    "9.6",
                                    "9.7",
                                    "10",
                                    "10.1",
                                    "10.2",
                                    "10.3",
                                    "10.4",
                                    "11",
                                    "11.1",
                                    "12",
                                    "12.1",
                                    "12.2",
                                    "12.3",
                                    "13",
                                    "13.1",
                                    "13.2",
                                    "13.4",
                                    "14",
                                    "14.1",
                                    "14.2",
                                    "15",
                                    "15.1",
                                    "15.2",
                                    "16",
                                    "16.1",
                                    "16.2",
                                    "16.3",
                                    "17",
                                    "17.1",
                                    "17.2",
                                    "17.3",
                                    "17.4",
                                    "18" };

    public static String[] patogolyNames = { "Control Adulto Sano",
                                    "Control De Niño Sano",
                                    "Patologia Respiratoria",
                                    "Virosis VRA",
                                    "Bronconeuminitis",
                                    "Asma",
                                    "Amigdalitis",
                                    "Patologias Digestivas",
                                    "Parasitosis",
                                    "Dolor Abdominal Inespecifico",
                                    "Gastritis / Reflujo",
                                    "Diarrea",
                                    "Estreñimiento",
                                    "Gea",
                                    "Hepatitis / Cirrosis",
                                    "Patologia Urológica",
                                    "ITU",
                                    "HBP",
                                    "Patologia Osteomuscular",
                                    "Dolor Articular",
                                    "Dolor Espalda / Lumbalgia",
                                    "Dolor Muscular",
                                    "Fracturas / Protesis",
                                    "Patologia Sistema Nervioso",
                                    "Cefalea / Humera / Vértigo",
                                    "Epilepsia",
                                    "Down",
                                    "Paralisis Cerebral",
                                    "Insomnio",
                                    "Patologia Dermatologica",
                                    "Dermatitis Atópica",
                                    "Dermatitis Infecciosas",
                                    "Vitiligo",
                                    "Otras Patologias Dermatologicas",
                                    "Patologia Ginecológica / Obstetricia",
                                    "Control Del Embarazo",
                                    "Menopausia",
                                    "Infecciones",
                                    "Dolor Menstrual",
                                    "Sequedad Vaginal",
                                    "Endometriosis/ Quistes",
                                    "Histerectomia",
                                    "Patologia Infecciosa",
                                    "Otitis Media",
                                    "Infeccion Ocular / Conjuntivitis",
                                    "Fiebres De Origen Tropical",
                                    "Varicela",
                                    "HTA",
                                    "Crisis Hipertensiva",
                                    "Nutrición",
                                    "Desnutricion",
                                    "Obesidad",
                                    "Malnutricion",
                                    "Patología Psiquiátrica",
                                    "Ansiedad",
                                    "Depresion",
                                    "Esquizofrenia",
                                    "DM",
                                    "Hiperglucemia",
                                    "Pie Diabetico",
                                    "Hematologia",
                                    "Anemia",
                                    "Insuficiencia Venosa / Varices",
                                    "Curas",
                                    "Herida Quirurgica",
                                    "Herida Traumatica",
                                    "Otras",
                                    "Patologia Oftalmica",
                                    "Cataratas",
                                    "Pterigion / Pingecula",
                                    "Estrabismo",
                                    "Ceguera",
                                    "Otros" };
}
